language: java
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: jdUmYVZHJHcwm0l/O76FSelqOUo8R6zXVYot08dd1dhRtlSmoiiz106GlHTV3EXlNVMaPXenU+zESIm+lEOC5brXXbPSUhBRc2BEjlOjkNGX71PtcuiAjOy4nUe/py+HllYDG+jeL0qNZzd0UaUN9aPtkMZSB1Qk2D0BOdwp+o1RzOehBjkQbEA8DRCnEmdWsffOVCXrSa60OIFebdntLVWETQHD6FYsPts57dOWOFZ4rOhaEu99YP/7Tc7Q0Dh+PRYeYowDlT2xPge6fDosP9sn746nYMT39gkTfU7t2XzZ2dcIsLA5yXjHKWk7o65RBJHimBfIgBlXgEIc00kuXonT4XYG8XFy3VmIzPw5XvI8S3knMtdyAPZWGn2WngzbJidejy+FxOzlGimPwbqepMF80+agFOii3jaxCxPLyBor48tmaKp0ByZAjqcWK8UqDtc427H52FQgxKNWmtF+rpCg1ds7MVbF0OlcBupVpx4WNA+fg7QqQDiXGSntSWmwMaAdVRpF2N7qtd3xX9tZ8jMQny9ys8q2cWCfrD1CahH0c+N/3jN6zypVfNXyB5H6maNQpldbt5YlXvFENu4krR4UdY1CuJgdmbtL9iZpLaL075CD4Vv7engmAJxfPUjr5lYMLattLwcJzexpyae485E2ktIq9Nl8C6dh6gT6Blw=
  file: target/nestedAvro-maven-plugin-$project_version.jar
  skip_cleanup: true
  on:
    repo: otahri/nestedAvro-maven-plugin
  name: $project_version
